<a href="https://colab.research.google.com/github/TamuroKensh1/gazou/blob/master/preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import sys
sys.path.append('/content/drive/My Drive/zemi/')

import ic_module as ic
import os.path as op

i = 0
for filename in ic.FileNames :
    # ディレクトリ名入力
    while True :
        dirname = input(">>「" + ic.ClassNames[i] + "」の画像のあるディレクトリ ： ")
        if op.isdir(dirname) :
            break
        print(">> そのディレクトリは存在しません！")

    # 関数実行
    ic.PreProcess(dirname, filename, var_amount=3)
    i += 1

>>「秋山竜次」の画像のあるディレクトリ ： /content/drive/My Drive/zemi/face/秋山竜次
>> /content/drive/My Drive/zemi/face/秋山竜次から68個のファイル読み込み成功
>>「山本博」の画像のあるディレクトリ ： /content/drive/My Drive/zemi/face/山本博
>> /content/drive/My Drive/zemi/face/山本博から60個のファイル読み込み成功
>>「馬場裕之」の画像のあるディレクトリ ： /content/drive/My Drive/zemi/face/馬場裕之
>> /content/drive/My Drive/zemi/face/馬場裕之から72個のファイル読み込み成功


In [24]:
import ic_module as ic

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)

>> 学習サンプル数 :  (600, 32, 32, 3)
>> 学習開始
Epoch 1/50
63/64 [============================>.] - ETA: 0s - loss: 1.1054 - accuracy: 0.3274
Epoch 00001: val_loss improved from inf to 1.09851, saving model to best.hdf5
64/64 [==============================] - 4s 61ms/step - loss: 1.1054 - accuracy: 0.3294 - val_loss: 1.0985 - val_accuracy: 0.3333
Epoch 2/50
63/64 [============================>.] - ETA: 0s - loss: 1.0986 - accuracy: 0.3452
Epoch 00002: val_loss improved from 1.09851 to 1.09653, saving model to best.hdf5
64/64 [==============================] - 4s 58ms/step - loss: 1.0982 - accuracy: 0.3471 - val_loss: 1.0965 - val_accuracy: 0.3333
Epoch 3/50
63/64 [============================>.] - ETA: 0s - loss: 1.0920 - accuracy: 0.4008
Epoch 00003: val_loss did not improve from 1.09653
64/64 [==============================] - 4s 57ms/step - loss: 1.0919 - accuracy: 0.4020 - val_loss: 1.1049 - val_accuracy: 0.3333
Epoch 4/50
63/64 [============================>.] - ETA: 0s - loss: 1.0954 - a

In [25]:
import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/zemi/face/test/image_1.jpg
>> 計算結果↓
[[1.0000000e+00 5.2610844e-08 3.2614810e-13]]
>> この画像は「秋山竜次」です。

>> 入力したい画像ファイル(「END」で終了) ： END


In [26]:
import glob
import ic_module as ic
import os.path as op

dirname = "/content/drive/My Drive/zemi/face/test"#input("フォルダ名：")
files = glob.glob(dirname + "/*.jpg")
cn1 = 0; cn2 = 0;
for imgname in files :
    kind = ic.TestProcess(imgname)
    if kind == 1:
        cn2 += 1
    cn1 += 1

print("学習・非学習含め正答率は" + str(cn2*1.0/cn1) + "です。")

>> 計算結果↓
[[1.0000000e+00 3.8100939e-08 4.3306613e-13]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[1.0000000e+00 5.2610844e-08 3.2614810e-13]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[9.9999952e-01 4.3841496e-07 1.3879292e-09]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[9.9999666e-01 2.9560504e-06 3.6128264e-07]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[9.985973e-01 8.291244e-04 5.735378e-04]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[9.9488032e-01 5.0997166e-03 1.9899919e-05]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[0.9052091  0.06255838 0.03223255]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[0.17004175 0.03947495 0.7904833 ]]
>> この画像は「馬場裕之」です。
>> 計算結果↓
[[0.448155   0.00538257 0.5464624 ]]
>> この画像は「馬場裕之」です。
>> 計算結果↓
[[0.5444278  0.00497761 0.45059457]]
>> この画像は「秋山竜次」です。
>> 計算結果↓
[[0.28143436 0.00347746 0.7150882 ]]
>> この画像は「馬場裕之」です。
>> 計算結果↓
[[0.26047125 0.00403918 0.7354895 ]]
>> この画像は「馬場裕之」です。
>> 計算結果↓
[[0.02562802 0.9717962  0.00257575]]
>> この画像は「山本博」です。
>> 計算結果↓
[[3.6892325e-02 9.6261805e-01 4.8970396e-04]]
>> この画像は「山本博」です。
>> 計算結果↓
[[0.05710332 0.93044597 0.01245061]]
